name: Update PSL catalog
on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - master

jobs:
  build_catalog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        activate-environment: catalog-env
        environment-file: environment.yml
        python-version: 3.8
        auto-activate-base: false

    - name: Run python script
      working-directory: ./Tools/Catalog-Builder/
      shell: bash -l {0}
      run: |
        pip install -e .
        cd catalog_builder
        python catalog.py

    - name: Commit new changes
      working-directory: ./
      shell: bash -l {0}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

        git add -A
        git commit --allow-empty -m "Update PSL-catalog on $(date +'%Y-%m-%d')"
        git push